spring:
  application:
    name: Config-Server1



eureka:
  client:
    service-url:
      defaultZone: http://localhost:9094/eureka
    register-with-eureka: true
    fetch-registry: true
    
  instance:
    prefer-ip-address: true 
         
